# MySQL Database configurations
db.url=jdbc:mysql://localhost:3306/carsharing_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=zone@123

# HikariCP pool configurations
db.pool.max-size=10
db.pool.idle-timeout=600000
db.pool.connection-timeout=30000
